### ISSUE TITLE
Problem with parents to [*]

### ISSUE THREAD

**Issue by tkarls** [patorjk/Extendible-BBCode-Parser#20]
Best javascript lib for BB code!

However, I need to use tags around multiple bullet tags. Like this:

````
[list][color=#FF0000][*]item1[*]item2[/color][/list]
````

I removed some of the allowed parents/children stuff but I have a problem with the fixStarTag function.

After that one is run I get:
````
[list][color=#FF0000][*]item1[/*][*]item2[/color][/*][/list]
````

As you can see the end tag of color is included inside the second [* ] tag.
I suppose one need to add so that the content inside the [* ][/* ] tag must not contain any end tags without matching start tags.

I'm not sure how to fix this and would appreciate some help.

**Comment by patorjk** [comment]
Sorry for the delay. I took a look and I believe this is because the only valid parent for a star tag is the list tag. When it's transformed into HTML, the star tag because an LI element (which is limited to certain parents):

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li

The easiest workaround would be to put the code you want for multiple bullets in each bullet. Other than that you could have multiple lists one after another and just adjust the margin style property. Or you could create an li tag (to use in place of the star tag) that required a closing tag. And the more I think about it, that last choice is probably what you want.

Removing the parent-child restriction makes things hard is because the star tag doesn't require a closing tag, so in order to add one in, the code looks for the closing list tag and places the closing star tag right before that. If you allow star tags to be wrapped in other tags, the code wont know where to put the closing star tag.

**Comment by tkarls** [comment]
Thanks for the reply!

Yes, I understand your reasoning. What I was trying to accomplish was to create bb code that hides the bullets by putting them in the same color as the background on a specific forum. By putting the color tag inside each one it is not working. This was needed to create vertical space in a poll since each poll option must be a one liner and there are no [br] tags... 

That BB code got rather complicated so I'm trying to build an online bb code builder for these types of poll posts on a forum I frequently visit. There the code works and rendered somewhat correct but I'm trying to use this lib for the preview as I have no access to the forum backend...

But I think from your reply that I will try to create a custom bullet tag with a closing tag to get the preview working and then transform that into the star tags when the code is copied to be pasted into the actual forum post.

I'm not sure my rambling made sense but thanks anyway :)
